[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "terrajin"
version = "1.0.0"
description = "Python Terrain generation Game framework"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "Sylvie Sylv Sylv"},
    {name = "Rawsie"}
]

dependencies = []

[tool.setuptools.packages.find]
where = ["src"]